- styles/styles.css
Fix #18 
Test URLs:
- After: https://issue-18--ingredion--aemsites.aem.live/
> Update styles.css with identified colors

- scripts/utils.js
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/es-mx/
- After: https://region-locale-fix--ingredion--aemsites.aem.live/na/es-mx/
> Fixing region locale util function

- blocks/callout/callout.css
- blocks/callout/callout.js
Fix #17 
Test URLs:
- After: https://issue-17-variant--ingredion--aemsites.aem.page/drafts/gfiscaletti/callout
> Issue #17.2: add transparent variant for callout block

- blocks/header-dropdown/header-dropdown.css
- blocks/header-dropdown/header-dropdown.js
- blocks/header/header.css
- blocks/header/header.js
- blocks/ingredient-select/ingredient-select.css
- blocks/ingredient-select/ingredient-select.js
- scripts/utils.js
Desktop styling of dropdowns complete.
Mobile styling will be handled in another ticket as we need direction from customer issue number 50.  
Fix #36
Test URLs:
- After: https://36-dropdowns--ingredion--aemsites.aem.live/na/en-us/
> Header dropdown desktop view

- blocks/header/header.css
- scripts/scripts.js
Test URLs:
- After: https://seo-fix--ingredion--aemsites.aem.live/na/en-us/
> adding aria-label to icon links for SEO

- blocks/hero/hero.css
- blocks/hero/hero.js
Fix #4 
Test URLs:
Before:
https://main--ingredion--aemsites.aem.live/drafts/ujjgupta/hero-news
https://main--ingredion--aemsites.aem.live/drafts/ujjgupta/hero-category
https://main--ingredion--aemsites.aem.live/drafts/ujjgupta/hero
After:
https://4-hero-improve--ingredion--aemsites.aem.live/drafts/ujjgupta/hero-news
https://4-hero-improve--ingredion--aemsites.aem.live/drafts/ujjgupta/hero-category
https://4-hero-improve--ingredion--aemsites.aem.live/drafts/ujjgupta/hero
> Improve authoring experience for hero block

- .github/workflows/update-pr-description.yaml
- blocks/header/header.css
- blocks/header/header.js
- scripts/scripts.js
Fixing small issue where line appears between the menu and dropdown
Added PR workflow to auto update the <branch> name.
Test URLs:
- After: https://small-fixes--ingredion--aemsites.aem.live/na/en-us/
> Small fixes

- blocks/cards/cards.css
- blocks/cards/cards.js
Fix #66
Test URLs:
- After: https://issue-66--ingredion--aemsites.aem.page/drafts/akupreyeva/cards
> 4 column cards block variant

- blocks/contact-us/contact-us.css
- blocks/contact-us/contact-us.js
- styles/styles.css
Fix #62
Test URLs:
- After: https://issue-62--ingredion--aemsites.aem.page/drafts/akupreyeva/contact-us
> Contact us block

- blocks/cards/cards.js
Fix #72 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/be-whats-next/better-nutrition-key-to-added-value-consumers-seek
- After: https://issue-72--ingredion--aemsites.aem.live/na/en-us/be-whats-next/better-nutrition-key-to-added-value-consumers-seek
> fixing issue 72, adding null check for imageAnchor

- blocks/color/color.css
- blocks/color/color.js
Fix #65
Test URLs:
- After: https://issue-65--ingredion--aemsites.aem.page/drafts/akupreyeva/color
> Color block

- scripts/back-to-top.js
- scripts/delayed.js
- styles/styles.css
Fix #51
Test URLs:
- After: https://issue-51--ingredion--aemsites.aem.live/na/en-us/
> Back to top button

- blocks/video/video.css
- blocks/video/video.js
Fix #76 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/categories/food/plant-based-dairy
- After: https://issue-76--ingredion--aemsites.aem.live/na/en-us/categories/food/plant-based-dairy
> adding video block

- blocks/related-ingredient/related-ingredient.css
- blocks/related-ingredient/related-ingredient.js
- styles/styles.css
Fix #61
Test URLs:
- After: https://issue-61--ingredion--aemsites.aem.page/drafts/akupreyeva/related-ingredient
> Related ingredient block

- styles/styles.css
Fix #<gh-issue-id>
Test URLs:
- After: https://theme-colors-fix--ingredion--aemsites.aem.live/
> Fix theme colors

- blocks/callout/callout.css
- blocks/callout/callout.js
- blocks/carousel/carousel.css
- blocks/carousel/carousel.js
- blocks/header/header.css
- blocks/modal/modal.css
- blocks/modal/modal.js
- blocks/related-ingredient/related-ingredient.css
- blocks/related-ingredient/related-ingredient.js
- blocks/video/video.css
- blocks/video/video.js
- scripts/back-to-top.js
- scripts/delayed.js
- scripts/scripts.js
- styles/styles.css
Attempting to re-merge issue 5 to main. 
Fix #5
Test URLs:
Before: https://main--ingredion--aemsites.aem.live/
After: https://issue-5--ingredion--aemsites.aem.live/drafts/gfiscaletti/carousel
> Issue 5 - (Re-merge after Github failure)

- blocks/quote/quote.css
- blocks/quote/quote.js
Fix #65 
Test URLs:
- After: https://issue-65-fix--ingredion--aemsites.aem.page/drafts/akupreyeva/quote
> issue-65.2: rename color block to quote

- templates/article-detail/article-detail.css
- templates/article-detail/article-detail.js
Fix #25 
Test URLs:
- After: https://issue-25--ingredion--aemsites.aem.page/drafts/akupreyeva/article-detail
> Rename news-detail to article-detail

- blocks/table/table.css
- blocks/table/table.js
Fix #103 
Test URLs:
- After: https://issue-103--ingredion--aemsites.aem.live/drafts/gfiscaletti/table-variants
> Add formulation and list variant for table block

- blocks/form/form.css
- blocks/form/form.js
- scripts/scripts.js
- styles/styles.css
Fix #98 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/drafts/ujjgupta/contact-supplier-page
- After: https://98-style-dropdown--ingredion--aemsites.aem.live/drafts/ujjgupta/contact-supplier-page
> 98 style dropdown

- blocks/author/author.css
- blocks/author/author.js
- blocks/contact-us/contact-us.js
- blocks/quote/quote.js
- blocks/related-ingredient/related-ingredient.js
- scripts/scripts.js
- templates/article-detail/article-detail.js
Fix #82 
Test URLs:
- After: https://issue-82--ingredion--aemsites.aem.page/drafts/akupreyeva/article-detail
> Author block

- templates/article-list/article-renderer.js
Fixing issue with article list
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/news-events/news
- After: https://artile-list-fix--ingredion--aemsites.aem.live/na/en-us/news-events/news
> Article list fix

- blocks/form/form.css
- blocks/form/form.js
- blocks/modal/modal.css
- blocks/modal/modal.js
- scripts/scripts.js
Fix #88 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/drafts/ujjgupta/modal
- After: https://88-form-in-modal--ingredion--aemsites.aem.live/drafts/ujjgupta/modal
> 88 form in modal

- blocks/related-ingredient/related-ingredient.css
- blocks/related-ingredient/related-ingredient.js
Fix #112
Test URLs:
- After: https://issue-112--ingredion--aemsites.aem.page/drafts/akupreyeva/related-ingredient
> Related-ingredient block fix: handle the case where there is no text content

- blocks/callout/callout.css
Fix #121 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/categories/biomaterials/oil-gas
- After: https://issue-121--ingredion--aemsites.aem.live/na/en-us/categories/biomaterials/oil-gas
> Fix order issue in callout CSS

- blocks/related-ingredient/related-ingredient.css
Fix #
Test URLs:
- After: https://related-ingredient-fix--ingredion--aemsites.aem.live/
> fix: increase specificity of selector in related-ingredient CSS

- blocks/form/form.js
- blocks/header/header.css
- blocks/header/header.js
- blocks/modal/modal.js
- blocks/related-ingredient/related-ingredient.js
- blocks/sample-cart/sample-cart.css
- blocks/sample-cart/sample-cart.js
- scripts/utils.js
Fix #37 
Add an ingredient using https://37-sample-cart--ingredion--aemsites.aem.live/drafts/ujjgupta/add-sample
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/sample-cart
- After: https://37-sample-cart--ingredion--aemsites.aem.live/na/en-us/sample-cart
> Implement sample cart functionality

- blocks/cta-icons/cta-icons.css
- blocks/cta-icons/cta-icons.js
Fix #105 
Test URLs:
- After: https://issue-105--ingredion--aemsites.aem.page/drafts/akupreyeva/cta-icons
> CTA icons block

- blocks/video/video.css
- blocks/video/video.js
Fix #87 
Test URLs:
- After: https://issue-87-2--ingredion--aemsites.aem.live/na/en-us/categories/food/plant-based-dairy
> Update video block

- helix-query.yaml
Fix #35 
Test URLs:
- After: https://issue-35--ingredion--aemsites.aem.live/
> Add global index to helix-query.yaml

- blocks/callout/callout.js
- blocks/cards/cards.css
- styles/styles.css
Fix #156 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-types/extracts
- After: https://issue-156--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-types/extracts
> Add dark-blue theme color for callout block

- blocks/locations/locations.js
Fix #144
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/es-mx/company/locations/
- After: https://issue-144--ingredion--aemsites.aem.live/na/es-mx/company/locations/
> Adding translations to map

- blocks/form/form.js
- scripts/utils.js
Fix #149 
Test URLs:
- Before: 
https://main--ingredion--aemsites.aem.live/na/en-us/company/contact-experts
https://main--ingredion--aemsites.aem.live/na/en-us/company/contact-supplier
- After: 
https://149-localize-forms-labels--ingredion--aemsites.aem.live/na/en-us/company/contact-experts
https://149-localize-forms-labels--ingredion--aemsites.aem.live/na/en-us/company/contact-supplier
> Generalize forms and localize form labels

- blocks/carousel/carousel.css
- blocks/carousel/carousel.js
- blocks/gallery/gallery.js
- scripts/scripts.js
Fix #167 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/company/meet-ingredion/sustainability
- After: https://issue-167--ingredion--aemsites.aem.page/na/en-us/company/meet-ingredion/sustainability
> Fix carousel style

- blocks/cards/cards.css
Fix #159 
Test URLs:
- After: https://issue-159--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-types
> Fix the rendering issue for the cards block

- blocks/cards/cards.css
- blocks/cards/cards.js
Fix #177 
Test URLs:
- After: https://issue-177--ingredion--aemsites.aem.page/na/en-us/
> Add slider for mobile slim cards

- templates/ingredient/ingredient.js
Fix #<gh-issue-id>
Test URLs:
- After: https://lint-fix--ingredion--aemsites.aem.live/na/en-us/
> fix lint errors

- blocks/cards/cards.css
Fix #230 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library/video-formulating-frozen-desserts-allulose
- After: https://issue-230--ingredion--aemsites.aem.page/na/en-us/solving-a-challenge/resource-library/video-formulating-frozen-desserts-allulose
> Add 2 column support to video card block

- blocks/callout/callout.js
- styles/styles.css
Fix #191 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/challenges/egg-replacement
- After: https://issue-191--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/challenges/egg-replacement
> added color `yellow` as block-option to callout.js, added color `yellow` to styles.css

- blocks/callout/callout.css
- blocks/callout/callout.js
- blocks/cards/cards.css
- blocks/cards/cards.js
- styles/styles.css
Fix #212
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/innovation-with-idea-labs/on-demand-learning-center
- After: https://issue-212--ingredion--aemsites.aem.page/na/en-us/solving-a-challenge/innovation-with-idea-labs/on-demand-learning-center
> Issue 212: make play button style global

- blocks/hero/hero.css
Fix #214 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/consumer-challenges
- After: https://issue-214--ingredion--aemsites.aem.page/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/consumer-challenges
> Issue 214: update hero align-left style

- blocks/article-list/article-renderer.js
- scripts/utils.js
Fix #238 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library
- After: https://issue-238--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library
> added undefined check for tags, added null check for published date

- styles/styles.css
Fix 206 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/challenges/nutrition-plus
- After: https://issue-206--ingredion--aemsites.aem.page/na/en-us/solving-a-challenge/challenges/nutrition-plus
> Issue 206: add global margins for sections

- blocks/search/search.js
- Updated the event date rendering in the search results to utilize the new parseEventDate function for improved date formatting.
- Enhanced the sorting logic for events by date to use parseEventDate, ensuring consistent date handling across the application.
Test URLs:
- Before: https://main--ingredion--aemsites.aem.livena/en-us/search?initialTab=&q=food
- After: https://event-date-fix--ingredion--aemsites.aem.live/na/en-us/search?initialTab=&q=food
> Refactor event date handling in search block

- blocks/cards/cards.css
- templates/article-detail/article-detail.css
- templates/article-detail/article-detail.js
- Added new CSS styles for the article detail page, including left text alignment for card bodies and improved layout for sections with a new container.
- Updated JavaScript to wrap sections in a container for better organization and styling, enhancing the overall user experience.
Fix 268
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/es-mx/resolviendo-desafios/innovando-con-idealabs/snacking/snacking-troubleshooting/la-mayoria-de-los-mexicanos-prefieren-ingredientes-naturales-en-sus-snacks
- After: https://issue-268--ingredion--aemsites.aem.live/na/es-mx/resolviendo-desafios/innovando-con-idealabs/snacking/snacking-troublesho …
> Fix for Article pages breaks when Section 

- blocks/callout/callout.js
- styles/styles.css
Fix #264 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/es-mx/compania/conoce-ingredion/business-integrity-ethics-compliance/code-of-conduct
- After: https://issue-264--ingredion--aemsites.aem.live/na/es-mx/compania/conoce-ingredion/business-integrity-ethics-compliance/code-of-conduct
> added pastel-green to callout.js and style.css

- templates/article-detail/article-detail.css
- templates/article-detail/article-detail.js
Fix #271 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/es-mx/resolviendo-desafios/innovando-con-idealabs/snacking/snacking-troubleshooting/resolvamos-los-problemas-mas-comunes-de-la-industria-con-nuestros-expertos
- After: https://issue-271--ingredion--aemsites.aem.live/na/es-mx/resolviendo-desafios/innovando-con-idealabs/snacking/snacking-troubleshooting/resolvamos-los-problemas-mas-comunes-de-la-industria-con-nuestros-expertos
> Don't add LinkedIn icon by default in article pages

- blocks/cards/cards.css
- blocks/cards/cards.js
Fix 212
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/innovation-with-idea-labs/on-demand-learning-center
- After: https://issue-212-cta--ingredion--aemsites.aem.page/na/en-us/solving-a-challenge/innovation-with-idea-labs/on-demand-learning-center
> Issue 212: fix CTA style for cards

- blocks/header/header.js
- blocks/ingredient-finder/ingredient-finder.css
- blocks/ingredient-finder/ingredient-finder.js
- blocks/search/content-renderer.js
- blocks/search/product-api-renderer.js
- scripts/add-to-cart.js
- scripts/product-api.js
- scripts/product-utils.js
- templates/ingredient/ingredient.js
Fix #224 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-finder
- After: https://224-ingredient-finder--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-finder
> 224 ingredient finder

- blocks/callout/callout.css
Fix #266 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/es-mx/ingredientes/tipos-de-ingredientes/extractos
- After: https://issue-266--ingredion--aemsites.aem.live/na/es-mx/ingredientes/tipos-de-ingredientes/extractos
> Removed fixed height in text callout block

- blocks/callout/callout.css
Fix #290
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/es-mx/compania/conoce-ingredion/business-integrity-ethics-compliance.html
- After: https://issue-290--ingredion--aemsites.aem.page/na/es-mx/compania/conoce-ingredion/business-integrity-ethics-compliance.html
> Issue 290: adjust links style in callout block

- blocks/header/header.js
- blocks/ingredient-finder/ingredient-finder.js
- blocks/related-ingredient/related-ingredient.js
- blocks/search/content-renderer.js
- blocks/search/search.js
- scripts/product-api.js
- scripts/product-utils.js
- templates/ingredient/ingredient.js
Fix #276 
Test URLs:
- Before: 
https://main--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-finder
- After: 
https://issue-276--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-finder
> Adding region/locale to product api configs

- scripts/product-api.js
Fix #291 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-finder
- After: https://test-cors-error--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-finder
> Adding ?initialTab= to api

- blocks/footer/footer.css
Fix #300 #302 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/es-mx/
- After: https://footer-css-fix--ingredion--aemsites.aem.live/na/es-mx/
> Fix footer css

- blocks/article-list/article-renderer.js
Fix #286
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library
- After: https://pagination-fix--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library
> Max Pagination butons fix

- blocks/table/table.css
Fix #154 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.page/na/en-us/categories/food/snacks
- After: https://issue-154--ingredion--aemsites.aem.page/na/en-us/categories/food/snacks
> Removed grey bar below table

- blocks/quote/quote.css
- blocks/quote/quote.js
- templates/article-detail/article-detail.css
Fix #265 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/news-events/news/ultratex-1311
- After: https://issue-265--ingredion--aemsites.aem.live/na/en-us/news-events/news/ultratex-1311
Example of the full-width quote block: https://issue-265--ingredion--aemsites.aem.page/na/es-mx/compania/expertise/the-stevia-institute/diet-metabolism-and-weight
> fix quote block style

- blocks/callout/callout.css
- blocks/callout/callout.js
Fix #308 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/company/meet-ingredion/business-integrity-ethics-compliance.html
- After: https://issue-308--ingredion--aemsites.aem.page/na/en-us/company/meet-ingredion/business-integrity-ethics-compliance.html
> Issue 308: add full-width variant to callout block

- blocks/hero/hero.js
- Refactor image selection to support both desktop and mobile views.
- Implement dynamic image replacement based on screen size using media queries.
- Remove unnecessary mobile image rows from the DOM.
- Optimize image loading with appropriate sizes for different breakpoints.
Fix #311, #313
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/drafts/dfink/hero
- After: https://hero-add-mobile-fix--ingredion--aemsites.aem.live/drafts/dfink/hero
- After: https://hero-add-mobile-fix--ingredion--aemsites.aem.live/drafts/dfink/hero-with-mobile
> Hero - add mobile image fix

- blocks/author/author.css
- blocks/author/author.js
- blocks/callout/callout.css
- blocks/footer/footer.css
- blocks/form/form.js
- blocks/header/header.css
- blocks/header/header.js
- blocks/related-ingredient/related-ingredient.css
- blocks/search/content-renderer.js
- blocks/search/search.css
- blocks/video/video.js
- scripts/scripts.js
- styles/fonts.css
- styles/styles.css
Fix #<gh-issue-id>
Test URLs:
- After: https://lhs-fix-new--ingredion--aemsites.aem.live/na/en-us/
> Lhs fix new

- blocks/related-ingredient/related-ingredient.js
Fix #327 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library/60-percent-reduced-sugar-chewy-granola-bar
- After: https://issue-327--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library/60-percent-reduced-sugar-chewy-granola-bar
> Using product heading for product name

- blocks/header/header.js
- Added loadTranslations and translate functions to improve localization.
- Updated search form action to include translated search text for better user experience.
Test URLs:
- After: https://search-locale-fix--ingredion--aemsites.aem.live/
> Added translations to header.js for search path

- templates/article-detail/article-detail.css
Fix #352 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/be-whats-next/whats-next-in-clean-label
- After: https://issue-352--ingredion--aemsites.aem.live/na/en-us/be-whats-next/whats-next-in-clean-label
> Added default padding to article page when screen is less than 1080px

- blocks/article-header/article-header.css
- templates/formulation/formulation.css
- Increased font size and adjusted margins for h2 in article-header.
- Refined author block styles, including margin adjustments and font size changes.
- Added new styles for formulation gallery content, enhancing typography and spacing for h1, h3, and paragraph elements.
Fix #330
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/be-whats-next/advancing-sustainability-in-2024
- After: https://issue-330-350--ingredion--aemsites.aem.live/na/en-us/be-whats-next/advancing-sustainability-in-2024
Fix #350
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library/sangria-flavored-beverage
- After: https://issue-330-350--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library/sangria-flavored-beverage
> Update article-header and formulation styles

- blocks/callout/callout.css
Fix #359 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/company/meet-ingredion/sustainability/advancing-sustainability-in-2024
- After: https://issue-359--ingredion--aemsites.aem.page/na/en-us/company/meet-ingredion/sustainability/advancing-sustainability-in-2024
> Issue 359: add responsive padding and max-width to prevent text overflow

- styles/styles.css
Fix # 344
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/be-whats-next/ingredion-starch-capacity-expansion
- After: https://issue-344--ingredion--aemsites.aem.live/na/en-us/be-whats-next/ingredion-starch-capacity-expansion
> Remove text-transform property from button styles in CSS for consistency

- scripts/scripts.js
Fix #333
Fix anchor navigation highlighting for sections shorter than viewport
- Replaces IntersectionObserver-based section highlighting with position-based detection
- Uses viewport middle point as reference to determine active section
- Handles both scroll and click navigation consistently
- Fixes issue where multiple short sections would cause incorrect highlighting
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/company/meet-ingredion
- After: https://issue-333-2--ingredion--aemsites.aem.page/na/en-us/company/meet-ingredion
Other pages that weren't working with previous solution
Before:
1. …
> Issue 333: improve anchor nav accuracy

- blocks/gallery/gallery.js
Fix #431 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library/formulation-bay-leaf-hot-chocolate
- After: https://no-thumbnail--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library/formulation-bay-leaf-hot-chocolate
> No thumbnail

- styles/styles.css
Fix #427 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library/how-to-reduce-sugar-in-cookies-sweet-biscuits
- After: https://font-size--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library/how-to-reduce-sugar-in-cookies-sweet-biscuits
> font size correction

- blocks/cards/cards.css
Fix #409 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.page/na/es-mx/compania
- After: https://card-block-spacing--ingredion--aemsites.aem.page/na/es-mx/compania
> fix spacing on card block

- blocks/cards/cards.css
Fix #405
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-types/fibers
- After: https://issue-405--ingredion--aemsites.aem.page/na/en-us/ingredients/ingredient-types/fibers
> Issue 405: scope cards nav selectors

- blocks/header/header.css
Fix #442 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.page/na/en-us/
- After: https://issues-442--ingredion--aemsites.aem.page/na/en-us/
> Updated font size of utility nav

- templates/ingredient/ingredient.js
Fix #
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/ingredient?name=frigex-w-06818102
- After: https://hide-product-type--ingredion--aemsites.aem.live/na/en-us/ingredient?name=frigex-w-06818102
> Add a null check for product type in pdp pages.

- blocks/cards/cards.css
Fix #418 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-types/plant-proteins
- After: https://418-center-cards--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-types/plant-proteins
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-types/tapioca/tapioca-starch
- After: https://418-center-cards--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-types/tapioca/tapioca-starch
> updated grid-template-columns auto repeat

- blocks/header/header.js
Fix #365 
Test URLs:
- After: https://issue-365--ingredion--aemsites.aem.live/na/en-us/
> Fix header search

- blocks/callout/callout.css
Fix #417 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/innovation-with-idea-labs/catalyst-program
- After: https://issue-417-2--ingredion--aemsites.aem.page/na/en-us/solving-a-challenge/innovation-with-idea-labs/catalyst-program
> Issue 417.2: adjust max-width to fit more text in callout

- blocks/carousel/carousel.css
Fix #453 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.page/na/es-mx/resolviendo-desafios/libreria-de-recursos/i2s-brief-yummy-dairy
- After: https://carousel-margin--ingredion--aemsites.aem.page/na/es-mx/resolviendo-desafios/libreria-de-recursos/i2s-brief-yummy-dairy
> Carousel Spacing

- blocks/header/header.css
- blocks/header/header.js
Fix #309 
Test URLs:
- After: https://issue-309--ingredion--aemsites.aem.live/na/en-us/
> Fix: language selector on click, not on hover

- blocks/header-dropdown/header-dropdown.css
- blocks/header/header.js
- blocks/ingredient-finder/ingredient-finder.js
- blocks/search/product-api-renderer.js
Fix #450 
Test URLs:
- After: https://header-issues--ingredion--aemsites.aem.page/na/en-us/
> Header issues

- blocks/callout/callout.css
- blocks/related-ingredient/related-ingredient.css
- styles/styles.css
Fix #461 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-product-families/astraea-allulose
- After: https://issue-461--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-product-families/astraea-allulose
> Fix related ingredient mobile CSS

- blocks/header/header.css
- blocks/ingredient-finder/ingredient-finder.js
Fix #395 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-finder
- After: https://issue-395--ingredion--aemsites.aem.live/na/en-us/ingredients/ingredient-finder
> Scroll to results ingredient finder search

- blocks/article-list/article-list.css
- blocks/article-list/article-list.js
- blocks/article-list/article-renderer.js
- icons/external-link.svg
- Added margin to the close icon in article cards.
- Introduced a featured card style with a background color and external link icon.
- Updated article card structure to include a featured tag and conditional CTA button.
- Implemented a normalization function for article tags to improve consistency in filtering.
Fix #161
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library?tags=resource+type+%2F+whitepaper
- After: https://issue-161--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/resource-library?tags=resource+type+%2F+whitepaper
> Added Featured / Gateway / Redirect content in article-list block

- scripts/scripts.js
- styles/styles.css
Fix #445 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.page/na/en-us/footer/footer
- After: https://new-tab-links--ingredion--aemsites.aem.page/na/en-us/footer/footer
> new-tab-script

- blocks/callout/callout.css
Fix #499 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.page/na/es-mx/ingredientes
- After: https://issue-499--ingredion--aemsites.aem.page/na/es-mx/ingredientes
> callout-image block css changes

- blocks/author/author.js
Fix #410 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/company/meet-ingredion/executive-leadership-team/gray
- After: https://issue-410--ingredion--aemsites.aem.live/na/en-us/company/meet-ingredion/executive-leadership-team/gray
> Add new line support in author description per locale

- tools/importer/helper.js
- tools/importer/solving-a-challenge.js
Fix #489 #320 
Test URLs:
- After: https://import-fixes-1--ingredion--aemsites.aem.live/
> import script updates

- blocks/cards/cards.css
Fix #467 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.page/na/en-us/solving-a-challenge/challenges/metabolic-health
- After: https://card-layout-for-single-card--ingredion--aemsites.aem.page/na/en-us/solving-a-challenge/challenges/metabolic-health
> Image card too big

- blocks/header-dropdown/header-dropdown.css
- blocks/header/header.css
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us
- After: https://be-whats-next-fixes--ingredion--aemsites.aem.page/na/en-us
> Styling fixes for be-whats-next dropdown

- blocks/callout/callout.css
Fix #371 
Test URLs:
- Before: 
- https://main--ingredion--aemsites.aem.live/na/en-us/company/expertise/texturants/lets-talk-texture
- https://main--ingredion--aemsites.aem.live/na/en-us/
- https://main--ingredion--aemsites.aem.live/na/en-us/categories/beverages/flavored-water-and-carbonated-beverage
- After:
- https://update-callout-css--ingredion--aemsites.aem.live/na/en-us/company/expertise/texturants/lets-talk-texture
- https://update-callout-css--ingredion--aemsites.aem.live/na/en-us/
- https://update-callout-css--ingredion--aemsites.aem.live/na/en-us/categories/beverages/flavored-water-and-carbonated-beverage
> Updating css for callout block

- blocks/cta-icons/cta-icons.css
Fix 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.page/na/en-us/company/meet-ingredion/resources
- After: https://issue-447--ingredion--aemsites.aem.page/na/en-us/company/meet-ingredion/resources
> Removed fixed width from cta-icons block

- blocks/cards/cards.css
Fix #526 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/es-mx/resolviendo-desafios/desafios/nutricion-por-reduccion
- After: https://cards-center-align--ingredion--aemsites.aem.live/na/es-mx/resolviendo-desafios/desafios/nutricion-por-reduccion
> Slim cards center alignment

- tools/importer/helper.js
Fix #
Test URLs:
- After: https://import-changes--ingredion--aemsites.aem.live/
> Import changes

- blocks/header-dropdown/header-dropdown.css
- blocks/header-dropdown/header-dropdown.js
- scripts/martech.js
Fix #559 
Test URLs:
- After: https://issue-559--ingredion--aemsites.aem.live/na/en-us/?martech=off
- https://issue-559--ingredion--aemsites.aem.live/na/en-us/solving-a-challenge/innovation-with-idea-labs/catalyst-program?martech=off
- https://issue-559--ingredion--aemsites.aem.live/na/en-us/be-whats-next/crispy-vs-crunchy-the-science-behind-texture-that-sells?martech=off
> Making menu links clickable

- blocks/header-dropdown/header-dropdown.css
Fix #542 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/?martech=off
- After: https://issue-542--ingredion--aemsites.aem.live/na/en-us/?martech=off
> Removed text transform css on news tab

- blocks/video/video.css
Fix #589 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/sa/pt-br/categorias/alimentos/panificacao?martech=off
- After: https://issue-589--ingredion--aemsites.aem.live/sa/pt-br/categorias/alimentos/panificacao?martech=off
> Fixed video close button issue

- blocks/footer/footer.css
- blocks/header/header.css
Fix #554 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.page/apac/sc-cn/be-whats-next/own-the-and?martech=off
- After: https://issue-554--ingredion--aemsites.aem.live/apac/sc-cn/be-whats-next/own-the-and?martech=off
> Fixed spacing issue on header and footer

- scripts/product-api.js
Fix #
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/es-mx/?martech=off
- After: https://cloud-api-fix--ingredion--aemsites.aem.live/na/es-mx/?martech=off
> Updated Cloud API call

- scripts/gtm-init.js
- scripts/martech.js
Test URLs:
- After: https://gtm--ingredion--aemsites.aem.live/na/en-us/
> GTM and DataLayer update

- blocks/article-list/article-renderer.js
- blocks/breadcrumbs/breadcrumbs.css
- blocks/breadcrumbs/breadcrumbs.js
- scripts/breadcrumbs.js
- styles/breadcrumbs.css
Fix #632 , #633 
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/en-us/news-events/events/?martech=off
- After: https://year-issue--ingredion--aemsites.aem.live/na/en-us/news-events/events?martech=off
> Fixed year and dataLayer issue

- scripts/martech.js
- scripts/utils.js
Fix  : https://jira.corp.adobe.com/browse/IAMIGR-135
Test URLs:
- Before: https://main--ingredion--aemsites.aem.live/na/kerr/products?martech=off
- After: https://issue-135--ingredion--aemsites.aem.page/na/kerr/products?martech=off
> Fixed: Martech country issue in kerrby page (issue-135)
